# This will boot 4 containers: 3 mongo as a cluster, and 1 to issue mongo commands to others
#
version: "3.5"
services:
  mongo3:
    image: mongo:3.6
    restart: always
    ports:
      - '27019:27017'
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--bind_ip", "0.0.0.0"]

  mongo2:
    image: mongo:3.6
    restart: always
    ports:
      - '27018:27017'
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--bind_ip", "0.0.0.0"]

  mongo1:
    image: mongo:3.6
    restart: always
    ports:
      - '27017:27017'
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--bind_ip", "0.0.0.0"]

  mongosetup:
    image: mongo:3.6
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "bash", "/scripts/mongosetup.sh" ]

networks:
  default:
    name: mongo-network